language: julia
os:
- linux

julia:
- 0.4

git:
  quiet: true

notifications:
  email: false
  slack:
    rooms:
    - secure: FFYIoXLlyIp3oyVbZJos0CX5em31dC9BENVWx1co48jeU9Ik2XzNkB8M0vH2YrrkdZJ/zrISmsQYg9+fa+4ABElheWtHVlau5V5YNThPx6SA4fDorTABretyvk5WjKDSA9p4zpvlUmvorJe5bm7VsCzM4C/833+oMRXt4AsQ0rgg8I5hwvSE922ttC3B+9U9kOO4kyRKgjIG0N1IFx+CMh3kldwqMYvISDVBeqRqmnAvQeYUqugfy96SLUj2xWcG8vUY0PgbP6QCZl76xSSUeypRTzwVG1Z45ye+7CeRyghJJbFK0i0metpdwLz9UCGQLpvHVLPYccYY3GTy5SQISKM1JLoulBr/PvJQe6ItUhK3SQp3/lbMIUmXUyUMdztFHt+RF0VcMrHc5bZwj5wAbLEs93xS8/WsEM0dmVWWaRtGRoYN0blOPD7HoceYsGNKevjkA9/XzVo8HfP7JO7GoZZ9D0sVh3aZ5RRcennA+XFTORg06zipuSmEn7zuH021cK0q3nBUFaoyS17U6mnQLCJzbOPiZPh48Xs21SnAZAwJgFDobs9NhXdXRJINtmoLzHSkXmng8BhHn2NmtB00lagwvxqlZq/+/tH22CJ1g2c3Lf1jdFyWYh74D2KEiTxHROEYpWoW7PAGxkjphP9O0ZQkXRCTXiyomDixB9a4r7U=
    - secure: Rp2s1f0azzwU6lj9fYcZ3+KDnXpZD4nGXl23pMdRKcRqISZFBlggK4lln3NDaDSyIE7kfWgYzDVmWkpkEe+daC4v1Kg8XXtimlIdm/fok8nksG3C9ySuWEzWA1o7J0JoiMgsSYhomHMOp9Xy1hd8lMQr37hVX1B9h4jISlFo8DrS50hUF9r8Q/cZeUTxGzP3DZ2pm9DB6okTML0dR73z5gCaHRbQS9JaLOsQbG4mMff9fVCSViPMUJ57Givp9jiIFQIewJiMaQEAqL48AZ09F7Jz5WrPHgwCoqA5RzyQnZM3OMlPPdt8rX06hBdTtgGesKNbjyUhFO/lHcg9yXfOxshrZIRiGobV5n1uXMtl0Nz8+KZZYQ9Tw1fAV1AMN0k+SPeuZkHqTYIpfB38czdhWcbFs+bfe2uDrxcDR0IBk1odfRNfkpEw6zMQFv6IvPyizDS1bsu7IzdANIEkubpYL2fYA+PnkvRZl62QvwkSOIUnfP0cn9jg4OlnZ1lNdQ+/DSX5ZEqvr7qSqXQTA7q7QWH3bRZkMxQdPK9pEAwCPnQx6YvX7eUWpaumNFGs3bGemEsl0CtLmaX2/HMJrJ75rffMQxLK4kAcJXqSjJ89atfppMwweGixkZCxq4Wmv5HWbb3kVPoQdyZY2MCg4Z+Og8fqR+LbxLQm0VvW1nfvkO0=

env:
  global:
  - secure: mO7kiWHPrD7P8ON1QvkNbsFZVZVtgWee+by9NmxbdBhNuub/VGMakWo1AdZvlBtmAXQfu40zXqWq/1mY1UJqy7dkTtPyokINfxzQSFZsypom2glf4WAdKSBuOb31F8SOS0QehuVrZKKCcRofzv139ETKjrK3TFnPVx5I3dcSEBL5wwfWjOSbsjowsjUnLLLMZNeMcu3O89GhpQITbFofDKRPFwXoEhc+lbf0dGcO9V2sNFQK3RG/XrvZDo4auWHPFUX52yi8Kk7Iol9kuiTCHKaZWevLiw+LLKG35TpeHRp+CPQsEB5yvw7Sg/5yoBNkw0rlj0x1+dJ/yqba3Yt8EOMMG81it9/tJuRC3lEuvAiQhjalI2tXqV5MdmGe/9uVzT47fwz0PHP3jYbOVhhx4KWJTxgkT92CAaQuO4xYcCnAyMi7j+rIuYA70nO4cnjrbnQQ3XZwEmyufL5xusMIwNsEKQbIdRF+kPfqva722wM96YxwFydW8N2njfl1ZNNQpqJ7+TQklKKWl1aAoVVGFLP5uxCpnblbhY8I7sixmN4g7e4/OYa6LUEvMpp7YRHXxWzq3rwFfksrRaNC3omeGBkTDMmxW8RCqIy7JK5dnVPouA84F1CkYLogOtfpNahFXVVeDrP6Fo3VHgUEATqCqo3lDDRM4+C9oY+sXitDIi4=

  matrix:
  # Production
  - mPulseAPIEndpoint: https://mpulse.soasta.com/concerto

  # QA
  #- secure: BKiNdpm3oJrZ9TfffI5n4lJzMf4jV9OVoQr+LoY1vFzLhtk0P97mpbu67NuhWoyk3x+G92Js1uhlHhFWsxITRD8LQBZP7m41I6W0xkOYWPwA68kCghXJsTaa/EaUy/3Xs5kxNMqu6dwhg0RZNsdUGS5MapZ3tXlGNSpZ9BXuRDW1pzfp0oYCzpGTY+HDNtC5fulUu888g+kfRY2VN7j2G7mZoBp4gd+phdNgVBBb7Mk+Z6oIE4DwzR33L1CsF+cdYz+BDm4FwNmvCFMrLtYGuSJlvG8iAGiK64+1e5pPVyty5Ag6WA1Mj9+d81mPZdg15nNXgm2FQJB0Ja9xHRv3En1t3eHl0YVkONro5aMQGnVbXSm1HE3BVpm74MlSpxtXpJgHYAUdiafqCrnl8fnbwSb8zbmRyg4EQQkbQz6PUFvY1KDKSPDhCVIqs9qa6d/2Jy3WnI2EbzrAFQemrKgWXVHsx3LUPcz7beqt4QNlaJGv7Uj52waed0ptDFNkf0GV5pWqBbkYuDDcs9sgscbLeXpNvZGqAX8Nw83CKa1E9XmPzEa80tbFkhnOpNbfYpCqQbBzjirSr3K2ED8CdQtjOmHX7ZFQSLUknF99JcD+NZGeqoMi0t0YO455UCuHAJqzvGIQp8cB7qWSZ0ckLl+uiTWy0ePuMwLV2vJwpbA2AFA=
